#!/bin/sh

# /usr/lib/openarena
FS_BASEPATH=/usr/lib/openarena

ENGINE="/usr/lib/omega-engine/omega-engine"

# we're a standalone game
CVARS="+set fs_basepath $FS_BASEPATH"

exec ${ENGINE} ${CVARS} "$@"
